In [ ]:
#----------------BLINKIT DATASET --------#

#importing and understanding data
import pandas as pd
df=pd.read_csv('/content/blinkit_dataset.csv')
df.head()

,product_id,product_name,category,brand,price,discount_pct,final_price,rating,num_reviews,delivery_time_min,...,is_organic,packaging_type,weight_g,shelf_life_days,reorder_level,demand_index,date_added,expiry_date,offer_type,delivery_status
0,1,Tata Organic Grocery 300,Grocery,Tata,199.78,25,149.84,4.5,146,37,...,True,Can,750,212,15,73,2023-11-27,2024-06-26,NaN,On-Time
1,2,Mother Dairy Lite Dairy 275,Dairy,Mother Dairy,44.32,30,31.02,4.0,264,36,...,False,Jar,1000,17,24,25,2024-08-07,2024-08-24,NaN,Delayed
2,3,P&G Classic Personal 439,Personal Care,P&G,501.13,0,501.13,3.7,69,17,...,True,Jar,1000,1463,25,100,2024-03-03,2028-03-05,FreeDelivery,On-Time
3,4,Dettol Fresh Household 771,Household,Dettol,627.17,0,627.17,3.9,103,23,...,True,Bottle,200,1143,18,15,2024-08-07,2027-09-24,NaN,On-Time
4,5,Minute Maid Daily Beverages 264,Beverages,Minute Maid,101.69,15,86.44,4.3,422,10,...,True,Can,300,363,30,6,2024-07-04,2025-07-02,NaN,On-Time

In [ ]:
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         13000 non-null  int64
 1   product_name       13000 non-null  object
 2   category           13000 non-null  object
 3   brand              13000 non-null  object
 4   price              13000 non-null  float64
 5   discount_pct       13000 non-null  int64
 6   final_price        13000 non-null  float64
 7   rating             13000 non-null  float64
 8   num_reviews        13000 non-null  int64
 9   delivery_time_min  13000 non-null  int64
 10  city               13000 non-null  object
 11  seller             13000 non-null  object
 12  stock              13000 non-null  int64
 13  sold_quantity      13000 non-null  int64
 14  profit_margin_pct  13000 non-null  float64
 15  is_organic         13000 non-null  bool
 16  packaging_type     13000 non-null  object
 17  weight_g           13000 non-null  int64
 18  shelf_life_days    13000 non-null  int64
 19  reorder_level      13000 non-null  int64
 20  demand_index       13000 non-null  int64
 21  date_added         13000 non-null  object
 22  expiry_date        13000 non-null  object
 23  offer_type         6456 non-null   object
 24  delivery_status    13000 non-null  object
dtypes: bool(1), float64(4), int64(10), object(10)
memory usage: 2.4+ MB

,product_id,price,discount_pct,final_price,rating,num_reviews,delivery_time_min,stock,sold_quantity,profit_margin_pct,weight_g,shelf_life_days,reorder_level,demand_index
count,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000
mean,6500.500000,267.303356,9.959231,240.735212,4.196931,255.000308,27.558769,110.140538,162.400077,22.652708,536.130769,397.555385,21.627769,43.380462
std,3752.921085,199.665148,8.575017,182.405552,0.475863,152.933513,7.139059,19.589137,132.742425,10.088389,406.997451,483.540218,3.928429,27.076935
min,1.000000,10.180000,0.000000,8.140000,2.500000,1.000000,10.000000,52.000000,0.000000,5.000000,100.000000,2.000000,10.000000,0.000000
25%,3250.750000,122.972500,0.000000,108.790000,3.900000,138.000000,23.000000,95.000000,54.000000,13.900000,250.000000,13.000000,19.000000,22.000000
50%,6500.500000,220.240000,10.000000,197.185000,4.200000,219.000000,27.000000,110.000000,120.000000,22.900000,400.000000,231.000000,22.000000,38.000000
75%,9750.250000,350.500000,15.000000,316.882500,4.500000,355.000000,32.000000,125.000000,253.000000,31.400000,750.000000,564.000000,25.000000,63.000000
max,13000.000000,999.930000,30.000000,998.920000,5.000000,1050.000000,56.000000,169.000000,720.000000,40.000000,2000.000000,1825.000000,33.000000,100.000000

In [ ]:
df.isnull().sum()

product_id              0
product_name            0
category                0
brand                   0
price                   0
discount_pct            0
final_price             0
rating                  0
num_reviews             0
delivery_time_min       0
city                    0
seller                  0
stock                   0
sold_quantity           0
profit_margin_pct       0
is_organic              0
packaging_type          0
weight_g                0
shelf_life_days         0
reorder_level           0
demand_index            0
date_added              0
expiry_date             0
offer_type           6544
delivery_status         0
dtype: int64

In [ ]:
df['offer_type'].value_counts()

offer_type
FlatDiscount    2657
Cashback        1895
Buy1Get1        1262
FreeDelivery     642
Name: count, dtype: int64

In [ ]:
#handlle missing values
df['offer_type'] = df['offer_type'].fillna('No Offer')
df['offer_type'].value_counts()

offer_type
No Offer        6544
FlatDiscount    2657
Cashback        1895
Buy1Get1        1262
FreeDelivery     642
Name: count, dtype: int64

In [ ]:
#Feature enginerring
df['revenue'] = df['final_price'] * df['sold_quantity']
df['discount_value'] = df['price'] - df['final_price']
df['rating_category'] = pd.cut(
    df['rating'],
    bins=[0,2.5,4,5],
    labels=['Low','Average','High']
)

In [ ]:
#EDA
#1,Offer impact on  sales
df.groupby('offer_type')['sold_quantity'].mean().sort_values(ascending=False)

offer_type
Cashback        164.865435
Buy1Get1        164.422345
FreeDelivery    162.998442
FlatDiscount    161.858487
No Offer        161.457366
Name: sold_quantity, dtype: float64

In [ ]:
#discountvs revenue
df.groupby('discount_pct')['revenue'].mean()

discount_pct
0     43852.893177
5     40372.380845
10    38995.209606
15    38422.096602
20    33988.563051
25    31783.166385
30    31121.198591
Name: revenue, dtype: float64

In [ ]:
#top category by revenue
df.groupby('category')['revenue'].sum().sort_values(ascending=False)

category
Household              1.206145e+08
Personal Care          9.977188e+07
Bakery                 6.323805e+07
Grocery                6.318989e+07
Fruits & Vegetables    4.756991e+07
Beverages              4.210465e+07
Snacks                 3.697250e+07
Dairy                  3.556570e+07
Name: revenue, dtype: float64

In [ ]:
#rating vs Sales
df.groupby('rating_category')['sold_quantity'].mean()

/tmp/ipykernel_1056/1818050815.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('rating_category')['sold_quantity'].mean()

rating_category
Low        119.750000
Average    165.729014
High       160.401088
Name: sold_quantity, dtype: float64

In [ ]:
#fast vs slow delivery
df['delivery_speed'] = df['delivery_time_min'].apply(
    lambda x: 'Fast' if x <= 30 else 'Slow'
)
df.groupby('delivery_speed')['rating'].mean()

delivery_speed
Fast    4.195583
Slow    4.199609
Name: rating, dtype: float64

In [ ]:
df.groupby('city')['revenue'].sum().sort_values(ascending=False)

city
Pune         53788632.78
Lucknow      52870665.80
Mumbai       52397493.56
Ahmedabad    51879748.75
Bengaluru    51682504.55
Jaipur       50795726.29
Delhi        50613081.00
Kolkata      49915302.76
Hyderabad    48878036.88
Chennai      46205938.07
Name: revenue, dtype: float64

In [ ]:
#hidden opportunity products
df[(df['rating'] > 4) & (df['sold_quantity'] < 50)][
    ['product_name','rating','sold_quantity']
]

                          product_name  rating  sold_quantity
4      Minute Maid Daily Beverages 264     4.3             48
12              ITC Premium Snacks 122     4.2             32
28         Patanjali Daily Grocery 796     5.0             10
29           Britannia Lite Snacks 121     4.4              5
31      Nivea Family Pack Personal 502     4.2             31
...                                ...     ...            ...
12921      Pepsi Organic Beverages 224     4.6             31
12934    Harpic Original Household 234     4.8             12
12951         Parle Premium Snacks 137     4.1             22
12953          Lay's Premium Snacks 98     4.8             23
12991     Britannia Classic Snacks 414     4.5              5

[1876 rows x 3 columns]

In [ ]:
df.to_csv("cleaned_blinkit_data.csv", index=False)